version: '3.8'

services:
  web:
    build: ./Farm

    command: gunicorn Farm.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - static_volume:/home/Farm/web/static
      - media_volume:/home/Farm/web/media
    
    expose:
      - 8000

    ports:
      - 8000:8000

    env_file:
      - ./.env.dev

  
  nginx:
    build: ./nginx

    volumes:
      - static_volume:/home/Farm/web/static
      - media_volume:/home/Farm/web/media
    
    ports:
      - 1337:80

    depends_on:
      - web

volumes:
  static_volume:
  media_volume:


      